### ISSUE TITLE
SimpleMigrator<DbConnection> needs to be SimpleMigrator<IDbConnection>

### ISSUE THREAD

**Issue by generik0** [canton7/Simple.Migrations#12]
Hi

Please use the IDbConnection interface instead of the DbConnection class.
You see I have a session factory that creates IDbConnection(s).

Possible?

**Comment by canton7** [comment]
`DbConnection` replaced `IDbConnection` as the ADO.NET connection base type in .NET 2.0, since it allows versioning. Since I expose the connection type to users in `Migration`, it makes an awful lot of sense to provide them with new and future improvements to ADO.NET.

I suggest updating your factory to output `DbConnections` instead of `IDbCOnnections`, to bring it into line with the changes made in .NET 2.0. If for some reason this is impossible, I recommend writing an adapter which subclasses `DbConnection` and wraps an `IDbConnection`.

**Comment by generik0** [comment]
That is very strange.
Dapper-dot-net by the stack mob "still" uses IDbConnection

From dapper mob:
Dapper is a NuGet library that you can add in to your project that will extend your IDbConnection interface.

And since I use dapper, then IDbConnection is the right way to do it...

**Comment by canton7** [comment]
Yeah, I guess since it doesn't *need* to take `DbConnection`, it doesn't. However if you look at the source you'll see that it does deal with `DbCommand` not `IDbCommand`, and it does this by casting (otherwise it wouldn't be able to do async queries). 

This did cause some problems when Microsoft wanted to drop the interfaces ([see here](https://github.com/dotnet/corefx/issues/3480)). As stated in the issue, the only reason that `IDbConnection` was brought forwards was to maintain compatibility with people who were (incorrectly) using it instead of `DbConnection`. It's one of those awkward catch-22 situations: things keep being supported because people keep using them, and people keep using things because they're still supported.

As I said in my previous comment, SimpleMigrations is a bit different to Dapper. With Dapper, the user calls into Dapper, and Dapper does some work. Dapper knows whether it needs `IDbConnection` or `DbConnection`. With SimpleMigrations, the user calls into us, *and then we call back into the user's code* (when we run the migration). Therefore by choosing `IDbConnection` we're not just restricting what we can do (which would be OK), but we're also restricting what the *user* can do in their migrations, which is less OK. 

See for example the issue about adding Async support. I can't do this if I'm using `IDbConnection`, but it is technically possible if I'm using `DbConnection` (although there are other reasons to avoid it).

**Comment by canton7** [comment]
> And since I use dapper, then IDbConnection is the right way to do it...

`DbConnection` implements `IDbConnection`. You can use `DbConnection` and Dapper will still work fine.

**Comment by generik0** [comment]
Interesting. I will look at it...

**Comment by generik0** [comment]
I have thought more about it over the night.
I still don't your point. The interface is just a a reference to the full DbConnection.
I really still believe that using IDbConnection is ther correct way to do it.

maybe adding overrides?

**Comment by canton7** [comment]
If you disagree, please address each of my points and explain why I'm wrong.

Dapper actually needs you to give it a `DbConnection`, otherwise [this cast](https://github.com/StackExchange/dapper-dot-net/blob/61e965eed900355e0dbd27771d6469248d798293/Dapper/SqlMapper.Async.cs#L239) won't work, among others. I'd rather explicitly state that I need a `DbConnection`, rather than pretending to accept any `IDbConnection` but actually needing it to be a `DbConnection`.

**Comment by canton7** [comment]
Also, explain to me how I'll ever add async support if I just accept `IDbConnection`?

**Comment by generik0** [comment]
What i don't like is to use real classes. 
I am an IoC / DI nerd. And think everything should be in interfaces.

The library i use the migrations (for sqlite unit tests) with actually is to make IoC better with dapper + uow +repo pattern:
https://github.com/generik0/Smooth.IoC.Dapper.Repository.UnitOfWork/tree/master/src/Smooth.IoC.Dapper.Repository.UnitOfWork.Tests

I simply don't like the IoC to resolve full class instances. Maybe it is just a preference.. 

I have overcome the limitation by initializing the mapping with the "session as DbConnection"
For me i don't need migrations Async. I do it on installation of the program. And when running unit test.

But what is wrong with making an override with IDbConneciton?

**Comment by canton7** [comment]
> What i don't like is to use real classes.

In IoC/DI terms, there's no difference between an interface and an abstract base class. They both define a contract which must be fulfilled by something. They can both be mocked in exactly the same way.

The difference is that Microsoft can add new methods to DbConnection (and DbCommand, etc), without breaking backwards compatibility - they add a default implementation of the method that does something sensible, and people can override it if they want to do something more specialised. The async methods do this.

> I have overcome the limitation by initializing the mapping with the "session as DbConnection"

You say you're a DI/IoC nerd, but this **completely** breaks that. If you try and inject a mock `IDbConnection`, this cast will fail, and you'll end up with an `ArgumentNullException`. If however you injected a mock `DbConnection`, everything would be just fine.

> For me i don't need migrations Async.

I didn't ask that. I asked how I would implement async in the future without `DbConnection`. Stop avoiding the question, please.

> But what is wrong with making an override with IDbConneciton?

Just try it :wink: (and *actually* try it - don't just replace a couple of `DbConnections` with `IDbConnections` and fail to try and run it). You'll quickly find that the connection type ends up everywhere, and is passed back to the user in the migrations. you'd have to have a completely separate library - you can't just add a method overload.

So far your only arguments have been "I don't like to use classes" and "I simply don't like the IoC to resolve full class instances", which are based on a flawed assumption about interfaces being somehow different to abstract classes in DI terms. I have made many points which you have failed to address. 

Right now, I feel like you're wasting my time. If you have actual, concrete reasons why `IDbConnection` is preferable to `DbConnection`, please describe them. Otherwise I consider this a issue a lack of education on your part.

**Comment by generik0** [comment]
"You say you're a DI/IoC nerd, but this completely breaks that". Yes it does. But only for my unit tests.
And i haven't IoCed your migrations...

**Comment by canton7** [comment]
My point being that you *could* be perfectly in line with IoC/DI by injecting a `DbConnection` (which is a contract, not a concrete implementation), but instead you're injecting an `IDbConnection` and casting it to a `DbConnection`.

There's a perfectly valid, perfectly clean, perfectly OK solution to your "problem", but you're ignoring that, doing something hacky, then blaming *me* because of it.

**Comment by generik0** [comment]
Yes i understand. And i have an interface that wraps the unique session conneciton / type anyway, so IDbConnecation is redundant.

I will have a look and get back to you. :-)

**Comment by generik0** [comment]
Well as i just wrote, i don't use the migrations with IoC.
My mistake was to mix the two together in my unit tests. I.e. getting the IoC to make the session for me.

my "Session" class also extends IDbConneciton. I will take your advice and make it inherit DbConnection instead. Then everything is solved...

Thanks for the dialogue :-)
