### ISSUE TITLE
Allow migration to run without code for a higher version

### ISSUE THREAD

**Issue by jlandersen** [canton7/Simple.Migrations#15]
Hi again

One more suggestion - it should be possible to allow the migration to run without exceptions being thrown, if a version in the versioninfo table exists that is higher than the max version found int he assembly.

In a team setting where multiple people work with feature branches (but uses the same database). Example:
Dev 1 adds migration 1 and 2 and runs that, and finalizes the changes and merges to master. 
Dev 2 adds migration 3 in a feature branch and runs that against the development DB.
Other devs are now unable to run the application that runs migration on startup from the master branch, because they only have version 2 in the assembly, but version 3 is registered in the database. 

Another example is doing blue/green deployment to avoid downtime, in the case of doing a rollback. E.g. in our team we only do backwards compatible DB upgrades (e.g. adding columns). Let's say we deploy a version that performs a migration (call it migration version 7), but have to roll the application back to the previous version that contains migration version 6. It is now no longer possible to start up because the assembly has a max version lower than the one in versioninfo.

An option would be to handle the exception explicitly when running the migrator, but it may be worth considering to add some options to adjust this behaviour.

**Comment by canton7** [comment]
I think you case - only doing backwards compatible DB upgrades - is probably rather rare.

The assumption in SimpleMigrations is that if you're running code which has been written against database version 5, it will only work when run against database version 5. Under that assumption it's right that someone who's running code which only knows about database version 4 won't run against a database with version 5, and an application which only knows about database version 4 can't roll back from database version 5 to version 4.

I think this is a fairly common assumption, so I don't want to change this behaviour as the default.

One suggestion I have is to throw a specific exception when SimpleMigrations fails to load because the database is too new. Most people won't see a change in behaviour, but you could catch and swallow it (and not try and perform any migrations if you see it), which should work, I think?

**Comment by jlandersen** [comment]
A specific exception type would be good enough!

**Comment by canton7** [comment]
I can't think of anything else that's sensible TBH.

I could pretend that the `Load()` succeeded, but then I'd have to allow `MigrateToLatest()` to succeed. It would have to no-op if it didn't have data for the latest migration. I'd presumably also have to let `MigrateTo(n)` succeed, otherwise we don't have symmetry. However I can't assume that any migrations between the last one we have data for and the one the database is at exist (not everyone numbers their migrations sequentially), so we'd have weird unexpected behaviour.

Essentially I end up adding a lot of logic specific to your situation, to allow you to "run" (but not actually run) migrations which might or might not exist, and end up with a confusing model as a result. That's all going to need documenting, and people will have to read the docs to understand the weird behaviour: it won't be intuitive.

If instead I provide a means for you to identify the case where you don't have the necessary migration data, you can add your logic in a small handful of lines by deciding not to migrate in this case. The total number of lines is much smaller, and someone reading the code can figure out what's going on very quickly without having to find and read any docs.

... That's my thinking, anyway.

**Comment by canton7** [comment]
Does that look OK?

**Comment by jlandersen** [comment]
It does! As a suggestion, maybe simplify it to `MissingMigrationException` - Data does not add much to the name.  `MissingMigrationException` is refers directly to Migration types.

**Comment by canton7** [comment]
Yeah, fair point.
