### ISSUE TITLE
ConsoleLogger throws when no window is present

### ISSUE THREAD

**Issue by ydie22** [canton7/Simple.Migrations#20]
We are using the ConsoleRunner in an unattended build on VSTS. Internally, it uses a ConsoleLogger, but this causes a failure in such cases (no window present). Associated call stack:

```
An error occurred: System.IO.IOException: The handle is invalid.    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)    at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)    at System.Console.get_WindowWidth()    at SimpleMigrations.Console.ConsoleLogger.WriteHeader(String message)    at SimpleMigrations.SimpleMigrator`2.MigrateTo(Int64 newVersion)    at MyConsoleRunner.Run(String[] args) in d:\a\1\s\src\Data.Migrations\Program.cs:line 83
```

Additionally, the exception handling in ConsoleRunner.Run swallows all exceptions (catch (Exception ex2)), and only displays the exception message on the console, no call stack. This made it really hard to debug the issue. Can the code be changed like this, to obtain at least the call stack: Console.Error.WriteLine(string.Format("An error occurred: {0}", ex2));

**Comment by canton7** [comment]
I think any other console application would throw a wobbly if the console window wasn't available, so I'm not entirely convinced that I should handle that especially. You could always add a flag to make it silent. I'm happy to be convinced otherwise.

I think the original reason for hiding the call stack was that most exceptions which occur do not indicate a programmer error, but are instead an issue with the user input (bad migration given, etc). It wouldn't be hard to handle these cases though, and print the stack trace for the rest.

**Comment by canton7** [comment]
Aha, it's failing to get the width, I see. Yes I can correct that.

**Comment by canton7** [comment]
Bleh, NuGet's playing up, so I can't build the release on Appveyor. I'll try again later.

**Comment by ydie22** [comment]
Thanks for the fix. I'll update the package as soon as you can publish it.

**Comment by canton7** [comment]
Looks like there's a workaround: https://appveyor.statuspage.io/incidents/m2vdvw39kdk8. Building now.

**Comment by canton7** [comment]
Looks like the symbols aren't publishing, but the package is up there at least.
