### ISSUE TITLE
Targeting different providers

### ISSUE THREAD

**Issue by staterium** [canton7/Simple.Migrations#23]
Is it possible to target different providers with the same migrations? I am trying to target Sqlite and MSSQL simultaneously.

I imagine it would work if the SQL statements for both are identical, but is there a mechanism to cater for instances where an up or down migration requires provider specific SQL statements?

**Comment by canton7** [comment]
There's nothing built in, but I daresay it would be easy enough to achieve yourself.

Subclass `MigrationAttribute` and add a `string[] Targets` property. This means you can decorate your migration classes with e.g. `[Migration(1, "Some Description", "mysql", "mssql")]` to specify which providers it targets (you could use a flags enum instead of strings if you wanted, etc).

Implement your own `IMigrationProvider`. It will look a lot like the default `AssemblyMigrationProvider`, except that its constructor will accept a `target`. It will do the same scanning for migrations as the `AssemblyMigrationProvider`, except that it will also check the target.

That way when there's no difference in SQL, you can have the same migration target multiple databases. Where there are differences, you can have two classes which each target a specific database.

To be honest though, I would suggest looking at FluentMigrations - they provide a builder for writing database engine-agnostic migrations.

**Comment by staterium** [comment]
Thanks for the quick reply, I will try your suggestion. 

FluentMigrator is not an option because I need a package that targets .NetStandard as I'm building a PCL migrations library for use in Xamarin.

**Comment by staterium** [comment]
Your suggestion works perfectly, thank you. It changes the usage such that the user **has to** specify a provider when instantiating a SimpleMigrator, because omitting it means the MigrationProvider doesn't know which provider you want if none is specified.

**Comment by canton7** [comment]
>  It changes the usage such that the user has to specify a provider when instantiating a SimpleMigrator, because omitting it means the MigrationProvider doesn't know which provider you want if none is specified.

Yeah, I don't see a way around that unfortuntaly.

**Comment by canton7** [comment]
Closing, as I think we're done here.
