### ISSUE TITLE
File migrations support

### ISSUE THREAD

**Issue by MiroslavMikus** [canton7/Simple.Migrations#39]
Hey, I was wondering if I could write some migrations for my JSON files as well.

The backstory:
We have our base project and multiple customizing in different solutions. We would like to rename classes and update some values (and more) from our base project. These updates should be, at best, automatically applied for each customer solution. 

The idea is that:
- the version will be saved somewhere within our file. 
- And we can write our own `IMigration<DbConnection>` implementation. 
- then we can write just write our specific migration for each change.

The issue I'm facing right now is that the `IMigration<DbConnection>` uses the `DbConnection` class (maybe it could be `IDbConnection`).

Anyway, is this framework the right tool to do file migrations?

Thanks in advice

**Comment by canton7** [comment]
You *could* use Simple.Migrations, although I'm not sure there's much point to be perfectly honest. In the past I've done very similar things using an approach [like this](https://github.com/canton7/SyncTrayzor/blob/1ec7e4fadd5e7e64fb56348de630b85ccab35f07/src/SyncTrayzor/Services/Config/ConfigurationProvider.cs#L194-L366) (that's using XML and XDocument, but you could do exactly the same with JSON and e.g. JToken).

If you did want to use Simple.Migrations, you wouldn't be using `IMigration<DbConnection>`. Take a look at [this example](https://github.com/canton7/Simple.Migrations#example-using-sqlite-net) of using sqlite.net, where I write a custom database provider and migration base class for another library which doesn't use `DbConnection`: you can probably do something similar, although I'm not sure whether you'll have problems with the version being part of the json file you're migrating, rather than in a separate "table".

**Comment by MiroslavMikus** [comment]
Hey, many thanks for the quick response. 

About the implementation of `IMigration<DbConnection>`, it looks like the DbConnection class implements the IDbConnection (and others) interface. So if I go for the usage of Simple.Migrations (BTW is in our solution already in use), then I need at least to inherit from the DbConnection. I guess that in your example the `SQLiteConnection` does exactly that already.

Nevertheless, you helped me already :)

Thanks for the great lib

**Comment by canton7** [comment]
In my example, SQLiteConnection does not inherit from DbConnection at all.

`IMigration<TConnection>` is generic. [See here](https://github.com/canton7/Simple.Migrations/blob/4655dc69a8018efe2afc1f81f0ab91db26e49158/src/Simple.Migrations/IMigration.cs) `TConnection` can be anything -- it's not constrained in any way.

There's a `SimpleMigrator<TConnection, TMigrationBase>`, which has the same `TConnection` generic type. Then there's a subclass `SimpleMigrator` which constrains `TConnection` to `DbConnection`. The README uses the non-generic `SimpleMigrator` which uses `DbConnection`, but the sqlite-net example uses `SimpleMigrator<TConnection, TMigrationBase>` where `TConnection` is a `SQLiteConnection`. [See here](https://github.com/canton7/Simple.Migrations/blob/4655dc69a8018efe2afc1f81f0ab91db26e49158/src/Simple.Migrations/SimpleMigrator.cs)

**Comment by MiroslavMikus** [comment]
You are absolutely right! I take everything back.
Somehow I was checking the `Migration` class: `public abstract class Migration : IMigration<DbConnection>` and there is alredy the `DbConnection`.

Thanks for the clarification!
