### ISSUE TITLE
Prevent multiple migrations starting in parallel

### ISSUE THREAD

**Issue by ashleydw** [canton7/Simple.Migrations#7]
In an environment with multiple instances of the same application, starting applications with the migration  logic in the Startup will start multiple migrations that run in parallel. This can lead to race-conditions where one or more migrations may fail as they all have read that they should start migrations to bring the database up to the latest version.

I believe locking the `versioninfo` table with an exclusive lock may be the answer to this problem as it will prevent other migrations starting if one has already locked the table in its transaction.

In Postgres:  `LOCK TABLE versioninfo IN ACCESS EXCLUSIVE MODE;`

**Comment by canton7** [comment]
Hmm, fair request.

This is turning the VersionProvider into something a bit more - it's not just providing versions, it's also providing locking, and potentially other things. 

That's fine - we're still pre-1.0, and I can break things. I'll get onto this shortly.

**Comment by ashleydw** [comment]
Thanks for your quick response.

An alternative may be inserting the migration row into the versioninfo table immediately. The issue then is what if the transaction fails, the row must be removed.

**Comment by canton7** [comment]
OK, this gets slightly more complex the more I think about it.

We currently run each migration + its version table update in a single transaction. We need to do this so that individual migrations can disable transactions, as some databases don't allow some sorts of updates within transactions.

In order to open a lock for the duration of the entire migration, we need a separate transaction that's open for as long as we're running migrations. That means we need a separate connection, as some database don't allow multiple concurrent transactions on the same connection.

That's fine - we'll get people to pass in a `Func<IConnectionProvider>` rather than an IConnectionProvider...

**Comment by canton7** [comment]
Hmm, currently we update the version table in the same transaction as the migration is run. We'll have to abandon this approach if we want to use a lock on the version table to solve your issue... I need to have a think.

**Comment by canton7** [comment]
One approach could be...

For migrations in transactions:

1. Open transaction
2. Acquire table lock (blocking, with configurable timeout)
3. Test version table
4. If migration has already been applied, skip it
5. Otherwise, apply migration and update version table
6. Close transaction, releasing table lock

For migrations outside of transactions

1. Run migration
2. Open transaction
2. Acquire table lock (blocking, with configurable timeout)
3. Test version table
4. If migration has already been applied, skip updating the version table
5. Otherwise, update version table
6. Close transaction, releasing table lock

This means we still only have to use 1 connection, which is nice, and we still get the migration and table update running in the same transaction, which is also nice. It does mean that in a race, one application may apply some migrations, and another may apply other migrations. I can't think of a reason why this wouldn't be OK, other than some potentially confusing logs... Any thoughts?

**Comment by canton7** [comment]
An alternative is to abort immediately if we either fail to acquire the table lock, or do acquire it but find that someone else has already applied the migration. That might be neater, actually...

**Comment by ashleydw** [comment]
I don't think you should be concerned about the logging as applications spread across several machines often use a unified log.

I hadn't thought about some migrations having implicit transaction commits inside them; and you're correct, they could (probably would) cause issues.

Is it easier to think about inserting the versioninfo row immediately, running the migration, and if it throws an exception, catch it, rollback versioninfo (DELETE the row), and then re-throw the caught exception?

**Comment by canton7** [comment]
> Is it easier to think about inserting the versioninfo row immediately, running the migration, and if it throws an exception, catch it, rollback versioninfo (DELETE the row), and then re-throw the caught exception?

In order to do this, we'd need to run the update table query and the migration in different transactions, no? I think I want to avoid this on principle: where possible, we should use transactions to guarantee consistency, rather than creating fake transactions ourselves. 

I don't see that writing to the version table before entering the transaction helps, unless I'm missing something? You've got a read-modify-write situation unless you do the read/write inside a transaction, and if you do it inside a transaction then there's no difference between this and running the migration between the read and the write....

**Comment by canton7** [comment]
However, thinking that through has, I think, convinced me that we don't need a table lock. Using transactions is enough. So long as we read read and write the version table in the same transaction, the database will stop two transactions run at the same time from succeeding.

Of course, this doesn't apply to migrations run outside of a transaction. However we can't escape a read-modify-write situation in these cases (and it's up to the migration to be safe). We can, however, prevent us from writing the same version to the version table twice in this situation, by doing:

1. Read version table. Error if the migration we're about to run has already been run
2. Run migration.
3. Open a transaction. Read the version table again. If the new migration has been added, abort. If it isn't, add it. Commit.

**Comment by canton7** [comment]
Actually, the "abort if someone else is running migrations" approach is bad. It means that `.MigrateTo()` will return *before* all migrations have been applied, which could well cause bad problems.

**Comment by canton7** [comment]
Another approach: Postgres has pg_advisory_lock, and MySQL has GET_LOCK, which are advisory locks used outside the scope of a transaction ([see here](https://github.com/rails/rails/pull/22122/files). That might be a neater solution. Not sure if mssql supports the same...

**Comment by canton7** [comment]
I don't think multiple connections is going to work. If I ask the user for a `Func<IConnectionProvider>`, they're going to do this:

```csharp
var connection = new Connection(.,..);
var migrator = new SimpleMigrator(() => new ConnectionProvider(connection));
```

rather than this:

```csharp
var migrator = new SimpleMigrator(() => new ConnectionProvider(new Connection(.,..)));
```

**Comment by canton7** [comment]
Right, I decided to go with the approach of running each migration + version table update in its own individual transaction, reading the current schema version at the beginning of each transaction, and properly handling the case where it was changed under our feet. This should support all databases without the need for multiple connections, or or database-type-specific locking which might not be supported by all databases.

Work is underway, and I've got an implementation in place. It needs more testing, both against different databases and in different scenarios, before I'm happy to merge it.

**Comment by canton7** [comment]
Turns out that Postgres is racey when creating tables, even inside serialized transactions. So I'm having to go for a hybrid approach of both using clever transactions, and database-wide locks (for databases which support them).

**Comment by canton7** [comment]
... and MSSQL throws up, complaining of deadlocked transactions, if you try and get both transactions to do a read/modify/write of the VersionInfo table. There are no advisory locks here either, I think. This might make this approach dead in the water.

**Comment by canton7** [comment]
Right, I think the approach I was trying to follow is a no-go. Might be time for keeping separate connections for the migrations and the version table updates, so that the latter can keep an exclusive lock on the version table.

However that won't provide locking around creating the version table, which both postgres and sql server seem to have problems with... We can use an advisory lock for postgres.

The upside is that we can probably move transaction management into the migration base class, which simplifies things considerably.

**Comment by canton7** [comment]
Right! That approach works. I'm tidying up the docs and fixing the unit tests, then I'll get it merged.

**Comment by canton7** [comment]
Right, v0.9.7 is out, which should fix this.
